# Generated by Django 5.0.6 on 2024-07-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='AnnotatorID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
