# Generated by Django 5.0.6 on 2024-07-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_annotator_annotatorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataannotation',
            name='annotatorId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataannotation',
            name='badAudio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataannotation',
            name='isAnnotated',
            field=models.BooleanField(default=False),
        ),
    ]
