# Generated by Django 5.0.6 on 2024-07-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_dataannotation_annotatorid_dataannotation_badaudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataannotation',
            name='audio',
            field=models.CharField(max_length=255),
        ),
    ]
